### PR TITLE
CodeStyle - remove whitespaces

### PR DESCRIPTION
**Pull request by HerzScheisse**
for quite a while now i wanted to submit these code style changes... now while i'm updating my webtrees i used the chance to do it right away...

hope this is helpfull...

If you want, i can do this for the other modules too...

### CODE REVIEW

**Comment by ric2016** [comment]
> If you want, i can do this for the other modules too...

Let me check whether there is an option for this in my IDE (NetBeans). I'll definitely use the setting to remove trailing whitespace when saving files from now on.

**Comment by ric2016** [comment]
Apparently there is no way to batch remove trailing spaces in Netbeans. Did you use a tool/ IDE for this?

**Comment by HerzScheisse** [comment]
Hey,

Sorry for messing up this PR with my latest commit... I thought you added this already thats why I decided to close this...

For the formatting I was using a extension in Visual Studio Code, its not fully automated... but with the keyboard shortcuts kinda fast...

this is the extension... https://marketplace.visualstudio.com/items?itemName=eetami.whitespace-formatter 

If you want and if its practical for you to copy these changes back to your IDE, i can do this for you... and created the PRs for that...

**Comment by ric2016** [comment]
> I thought you added this already thats why I decided to close this...

No, I just fould the setting to remove trailing whitespace when editing, but no way to do this once for all files.

If there is no way to do this initial cleanup automated, I'm not doing it myself - But I'll accept PRs.

**Pull request closed without merging**
